<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mr</name>
   <tag></tag>
   <elementGuidId>817e9364-2a11-4690-ac69-7e7f2cd55bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_gender1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0f87e65e-0fc1-4bcc-b047-ed58d3e5f845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>id_gender1</value>
      <webElementGuid>1de7248c-7298-420c-b18a-41e182c85c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>bf0b2b1b-fa87-4df7-9c23-0962418b6eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							
						Mr.
						</value>
      <webElementGuid>96e3c3b9-19b0-4159-98ed-698acf5f6a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-creation_form&quot;)/div[@class=&quot;account_creation&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;radio-inline&quot;]/label[@class=&quot;top&quot;]</value>
      <webElementGuid>2af38d51-cff6-4b4e-9dec-b3bed0cde7b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account-creation_form']/div/div/div/label</value>
      <webElementGuid>7d8bf412-9bd5-4f95-8b9c-7f37edbb2cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::label[1]</value>
      <webElementGuid>d2d18e91-6c5e-4bf0-9ad8-7f7bb92996de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your personal information'])[1]/following::label[2]</value>
      <webElementGuid>2dc34583-5cdd-41d9-81c8-35d2e0f44a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mr.']/parent::*</value>
      <webElementGuid>7ffa4c82-80d5-4992-8365-2058a9284854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/label</value>
      <webElementGuid>223cc9e0-93bc-4d1f-ba4f-681dd5aaa9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
							
						Mr.
						' or . = '
							
						Mr.
						')]</value>
      <webElementGuid>9a33e285-5b0c-42dc-988e-e2ec2559269d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
