<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , rf, , ))_rf</name>
   <tag></tag>
   <elementGuidId>42e48a2c-dc91-4f1d-b467-d774931e52da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='rf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e91f3d23-dfab-4872-afad-b2ea18d5fcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>f617364c-dfcc-4a13-ab58-9288121aec1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e0085ed-8e2c-45d1-9f4d-d40950c8d5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>51ec360c-ed2c-4114-ab0c-0b7c240716e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>d226896b-aec4-40d1-86f1-a7d1bd025f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>eb716e53-85cb-4c94-99cd-eebb2d73b187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>if(xc==1)sc(this);</value>
      <webElementGuid>88bb629c-972c-4220-ba7c-f8f063fb68af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rf&quot;)</value>
      <webElementGuid>07723be2-8a8f-4bd2-8b58-aabbcda11f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='rf']</value>
      <webElementGuid>9006b6db-a0f8-4d83-bb28-5efdf979a65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>780c6aed-2d9e-4783-9cc9-20cb93905435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'about:blank' and @name = 'rf' and @id = 'rf']</value>
      <webElementGuid>000209fe-028e-4bc8-8924-e5460016901f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
